version: '3'
networks:
  laravel: null
services:
  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    restart: unless-stopped
    container_name: nginx
    ports:
      - '8000:8000'
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    depends_on:
      - php
    networks:
      - laravel
  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: php
    ports:
      - '80:9000'
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    networks:
      - laravel
  composer:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: composer
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    working_dir: /var/www/html
    depends_on:
      - php
    user: '${USER:-laravel}'
    profiles:
      - composer
    entrypoint:
      - composer
      - '--ignore-platform-reqs'
    networks:
      - laravel
  artisan:
    build:
      context: ./docker/composer
      dockerfile: Dockerfile
      args:
        - 'UID=${UID:-1000}'
        - 'GID=${GID:-1000}'
        - 'USER=${USER:-laravel}'
    container_name: artisan
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    working_dir: /var/www/html
    profiles:
      - artisan
    entrypoint:
      - php
      - /var/www/html/artisan
    networks:
      - laravel
  npm:
    image: 'node:alpine'
    container_name: npm
    volumes:
      - './src:/var/www/html'
      - '.env:/var/www/html/.env'
    ports:
      - '3000:3000'
      - '3001:3001'
    working_dir: /var/www/html
    profiles:
      - npm
    entrypoint:
      - npm
    networks:
      - laravel
